export const cartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART : 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM : 'REMOVE_ITEM',
    CLEAR_CART : 'CLEAR_CART',
    CART_FROM_DB:'CART_FROM_DB',
    UPDATE_CART:'UPDATE_CART'
};

